apiVersion: apps/v1
kind: Deployment
metadata:
  name: detor-deployment
  labels:
    app: detor
spec:
  replicas: 3
  selector:
    matchLabels:
      app: detor
  template:
    metadata:
      labels:
        app: detor
    spec:
      containers:
      - name: detor
        image: anraj/detor:v1
        ports:
        - containerPort: 5000
